// <auto-generated />
namespace Studio84.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Alter_Table_PhotoPost_Add_Column_ThumbPath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alter_Table_PhotoPost_Add_Column_ThumbPath));
        
        string IMigrationMetadata.Id
        {
            get { return "202003151951136_Alter_Table_PhotoPost_Add_Column_ThumbPath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
